name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: 
        - runner: windows-2019
          name: windows
          folder_name: build/windows/runner/Release
        - runner: macos-latest
          name: macos
          folder_name: build/macos/Build/Products/Release/*.app
        - runner: ubuntu-latest
          name: linux
          folder_name: build/linux/x64/release/bundle
    runs-on: ${{ matrix.os.runner }}
    steps:
    - 
      uses: actions/checkout@v3
    -
      name: Install Flutter deps
      if: runner.os == 'Linux'
      run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
    -
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
        cache-key: flutter-${{ matrix.os.name }}
        flutter-version: '2.8.1'
    - 
      name: Build enmitydebugger
      run: |
        flutter config --enable-${{ matrix.os.name }}-desktop
        flutter create .
        flutter build ${{ matrix.os.name }}
    -
      name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: enmitydebugger-${{ matrix.os.name }}
        path: ${{ matrix.os.folder_name }}
  upload-prerelease:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - 
      uses: actions/checkout@v3
    -
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts
    - 
      run: |
        for i in linux macos; do
        (
          cd ./artifacts/enmitydebugger-$i
          tar -czvf ./artifacts/enmitydebugger-$i.tar.gz *
        )
        done
        (
          cd ./artifacts/enmitydebugger-windows
          zip -r ../enmitydebugger-windows.zip *
        )
    - 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        shopt -s globstar
        SHORT_REV=$(git rev-parse --short HEAD)
        gh release create -p nightly-$SHORT_REV -t "Nightly $SHORT_REV" -n "$(git log -1 --pretty=%B)" ./artifacts/*.zip ./artifacts/*.tar.gz
    
