name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - 
      uses: actions/checkout@v3
    -
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
    - 
      run: |
        flutter config --enable-windows-desktop
        flutter create .
        flutter build windows
        ls build/windows/runner
    - 
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build/windows/runner/Release/
